const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const money=n=>'£'+Number(n||0).toFixed(2);const get=(k,d=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||JSON.stringify(d));return v}catch{return d}};const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function products(){const r=await fetch('products.json?v='+Date.now(),{cache:'no-store'});return r.json()}function bag(){return get('funkocouple-bag',[])}function inBag(id){return bag().some(x=>String(x.id)===String(id)&&(+x.qty||0)>0)}function wish(){return get('funkocouple-wishlist',[])}function updateCounts(){const b=bag().reduce((n,x)=>n+Math.max(0,+x.qty||0),0),w=wish().length;$$('.bag-count').forEach(e=>{e.textContent=b;e.style.display=b?'grid':'none'});$$('.wish-count').forEach(e=>{e.textContent=w;e.style.display=w?'grid':'none'});$$('[data-wishlist-id]').forEach(e=>{const on=wish().some(x=>String(x)===String(e.dataset.wishlistId));e.classList.toggle('saved',on);e.textContent=on?'♥':'♡'});}function toggleWish(id){let a=wish(),i=a.findIndex(x=>String(x)===String(id));if(i>=0)a.splice(i,1);else a.unshift(id);set('funkocouple-wishlist',a);updateCounts();document.dispatchEvent(new Event('wishlistchange'))}function addBag(id){let a=bag(),i=a.findIndex(x=>String(x.id)===String(id));if(i<0)a.push({id,qty:1});else a[i].qty=1;set('funkocouple-bag',a);updateCounts()}function removeBag(id){const a=bag().filter(x=>String(x.id)!==String(id));set('funkocouple-bag',a);updateCounts()}function toggleBag(id){if(inBag(id))removeBag(id);else addBag(id)}async function applySiteLogo(){try{const r=await fetch('site-config.json?v='+Date.now(),{cache:'no-store'});const cfg=await r.json();if(cfg.logo){document.querySelectorAll('img[src="logo.svg"]').forEach(img=>{img.src=cfg.logo})}}catch(e){}}
function header(){applySiteLogo();updateCounts();document.addEventListener('click',e=>{const w=e.target.closest('[data-wishlist-id]');if(w){e.preventDefault();e.stopPropagation();toggleWish(w.dataset.wishlistId)}});window.addEventListener('storage',updateCounts)}function card(p){const sold=+p.stock<=0;const saved=wish().some(x=>String(x)===String(p.id));return '<article class="card reveal" data-product-link="product.html?id='+encodeURIComponent(p.id)+'"><div class="pic">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.name)+'">':'<span class="placeholder">PRODUCT IMAGE</span>')+(sold?'<span class="sold">SOLD OUT</span>':'')+'<button class="heart '+(saved?'saved':'')+'" data-wishlist-id="'+esc(p.id)+'" aria-label="Wishlist">'+(saved?'♥':'♡')+'</button></div><div class="cardbody"><div class="tag">'+esc((p.categories||[p.category||'Collectible']).join(' · '))+'</div><h3 class="name"><a href="product.html?id='+encodeURIComponent(p.id)+'">'+esc(p.name)+'</a></h3><div class="price">'+money(p.salePrice&&p.salePrice<p.price?p.salePrice:p.price)+'</div><button class="add" data-add="'+esc(p.id)+'" '+(sold?'disabled':'')+'>'+(sold?'SOLD OUT':'ADD TO BAG')+'</button></div></article>'}function wireAdd(productsList,root=document){root.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b){const p=productsList.find(x=>String(x.id)===String(b.dataset.add));if(!p||+p.stock<=0)return;e.preventDefault();e.stopPropagation();toggleBag(p.id);b.textContent=inBag(p.id)?'REMOVE FROM BAG':'ADD TO BAG';return}if(e.target.closest('[data-wishlist-id]')||e.target.closest('a,button'))return;const cardEl=e.target.closest('[data-product-link]');if(cardEl)location.href=cardEl.dataset.productLink})}async function initShop(){const ps=await products(),grid=$('#productGrid'),search=$('#search'),sort=$('#sort'),count=$('#resultCount');const params=new URLSearchParams(location.search);if(search&&params.get('q'))search.value=params.get('q');const requestedCategory=params.get('category')||'';function render(){let a=ps.filter(p=>(!search.value||p.name.toLowerCase().includes(search.value.toLowerCase()))&&(!requestedCategory||(p.categories||[p.category]).includes(requestedCategory)));if(sort.value==='az')a.sort((x,y)=>x.name.localeCompare(y.name));if(sort.value==='za')a.sort((x,y)=>y.name.localeCompare(x.name));if(sort.value==='low')a.sort((x,y)=>(x.price||0)-(y.price||0));if(sort.value==='high')a.sort((x,y)=>(y.price||0)-(x.price||0));grid.innerHTML=a.length?a.map(card).join(''):'<div class="empty" style="grid-column:1/-1">No collectibles found.</div>';count.textContent=a.length+' collectible'+(a.length===1?'':'s');updateCounts()}[search,sort].filter(Boolean).forEach(x=>x.addEventListener('input',render));wireAdd(ps,grid);render()}
async function loadSiteConfig(){try{const r=await fetch('site-config.json?v='+Date.now(),{cache:'no-store'});return await r.json()}catch{return null}}function renderCategoryBanners(cfg){
  const root=$('#categoryZone');if(!root||!cfg?.categories)return;
  root.innerHTML='<div class="fc-category-grid-head"><div><div class="eyebrow">SHOP BY CATEGORY</div><h2>Find your collection</h2></div><a href="shop.html" class="fc-category-view-all">SHOP ALL →</a></div><div class="fc-category-grid">'+cfg.categories.map((c,i)=>{
    const name=String(c.name),key=name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),num=String(i+1).padStart(2,'0'),img=c.image?String(c.image):'';
    return '<a class="fc-category-card fc-cat-'+key+'" href="shop.html?category='+encodeURIComponent(name)+'"><span class="fc-category-art'+(img?' has-image':'')+'" aria-hidden="true">'+(img?'<img src="'+esc(img)+'" alt="">':'')+'</span><span class="fc-category-shade" aria-hidden="true"></span><span class="fc-category-num">'+num+'</span><span class="fc-category-name">'+esc(name)+'</span><span class="fc-category-arrow">→</span></a>'
  }).join('')+'</div>';
  requestCategoryLedColours();
}
function requestCategoryLedColours(){
  document.querySelectorAll('.fc-category-art.has-image img').forEach(img=>{
    const apply=()=>{
      try{
        const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
        canvas.width=24;canvas.height=24;ctx.drawImage(img,0,0,24,24);
        const data=ctx.getImageData(0,0,24,24).data;
        let r=0,g=0,b=0,n=0;
        for(let i=0;i<data.length;i+=4){
          const rr=data[i],gg=data[i+1],bb=data[i+2],a=data[i+3];
          if(a<180)continue;
          const max=Math.max(rr,gg,bb),min=Math.min(rr,gg,bb);
          if(max<55 || max-min<28)continue;
          const boost=max-min;
          r+=rr*boost;g+=gg*boost;b+=bb*boost;n+=boost;
        }
        if(!n)return;
        r=Math.round(r/n);g=Math.round(g/n);b=Math.round(b/n);
        img.parentElement.style.setProperty('--led-color',`rgb(${r}, ${g}, ${b})`);
      }catch(e){}
    };
    if(img.complete)apply();else img.addEventListener('load',apply,{once:true});
  });
} async function initHome(){const ps=await products(),grid=$('#featuredGrid');const a=ps.filter(p=>+p.stock>0).slice(0,4);
const cfg=await loadSiteConfig();renderCategoryBanners(cfg);const newProducts=$('#newBannerProducts');if(newProducts){const picks=ps.filter(p=>+p.stock>0).slice(0,3);newProducts.innerHTML=picks.map((p,i)=>'<div class="fc-new-item fc-new-item-'+i+'">'+(p.image?'<img src="'+esc(p.image)+'" alt="">':'<span>POP!</span>')+'</div>').join('')}const banners=$('.category-banner');
banners.forEach(banner=>{
  const track=banner.querySelector('.category-track');
  let startX=0,startY=0,index=0,moved=false;
  const go=i=>{index=Math.max(0,Math.min(2,i));track.style.animation='none';track.style.transform='translateX('+(-33.3333*index)+'%)'};
  banner.addEventListener('touchstart',e=>{if(!e.touches[0])return;startX=e.touches[0].clientX;startY=e.touches[0].clientY;moved=false;track.style.animation='none'},{passive:true});
  banner.addEventListener('touchmove',e=>{if(!e.touches[0])return;const dx=e.touches[0].clientX-startX,dy=e.touches[0].clientY-startY;if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){moved=true;e.preventDefault()}},{passive:false});
  banner.addEventListener('touchend',e=>{if(!moved)return;const endX=e.changedTouches[0].clientX,dx=endX-startX;if(Math.abs(dx)>45)go(index+(dx<0?1:-1))},{passive:true});
});
const hs=$('#homeSearch');if(hs)hs.addEventListener('submit',e=>{e.preventDefault();const q=$('#homeSearchInput').value.trim();location.href=q?'shop.html?q='+encodeURIComponent(q):'shop.html'});grid.innerHTML=a.length?a.map(card).join(''):'<div class="empty" style="grid-column:1/-1">New stock is being added soon.</div>';wireAdd(ps,grid);updateCounts()}async function initProduct(){const ps=await products(),id=new URLSearchParams(location.search).get('id'),p=ps.find(x=>String(x.id)===String(id)),root=$('#productRoot');if(!p){root.innerHTML='<div class="empty" style="margin:60px auto;max-width:900px">Product not found.<br><br><a class="btn" href="shop.html">BACK TO SHOP</a></div>';return}
const cats=(p.categories||[p.category||'Collectible']).filter(Boolean),price=Number(p.salePrice&&p.salePrice<p.price?p.salePrice:p.price),onWish=wish().some(x=>String(x)===String(p.id)),stock=Number(p.stock||0),sold=stock<=0;
document.title=p.name+' | Funko Couple';
let r=get('funkocouple-recent',[]).filter(x=>String(x)!==String(p.id));r.unshift(p.id);set('funkocouple-recent',r.slice(0,12));
root.innerHTML='<div class="product-detail"><div class="product-crumb">SHOP / '+esc(cats[0])+'</div><div class="product-detail-grid"><div class="product-gallery"><button class="product-wish '+(onWish?'saved':'')+'" data-wishlist-id="'+esc(p.id)+'" aria-label="Save to wishlist">'+(onWish?'♥':'♡')+'</button><div class="product-main-image">'+(p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.name)+'">':'<span class="product-image-placeholder">PRODUCT IMAGE</span>')+'</div></div><div class="product-info"><div class="product-category">'+esc(cats.join(' · '))+'</div><h1>'+esc(p.name)+'</h1><div class="product-detail-price">'+money(price)+(p.salePrice&&Number(p.salePrice)<Number(p.price)?'<span class="product-old-price">'+money(p.price)+'</span>':'')+'</div><div class="product-delivery">UK delivery available · Secure checkout</div><div class="product-specs"><div class="product-spec"><b>Status</b><span>'+esc(p.status||'Not specified')+'</span></div><div class="product-spec"><b>Condition</b><span>'+esc(p.condition||'Not specified')+'</span></div></div><div class="product-description">'+esc(p.description||'A collectible available from Funko Couple.')+'</div><div class="product-stock '+(sold?'sold':'')+'">'+(sold?'SOLD OUT':(stock===1?'ONLY 1 LEFT':stock+' IN STOCK'))+'</div><button class="product-add" data-product-add="'+esc(p.id)+'" '+(sold?'disabled':'')+'>'+(sold?'SOLD OUT':(inBag(p.id)?'REMOVE FROM BAG':'ADD TO BAG'))+'</button><button class="product-save '+(onWish?'saved':'')+'" data-wishlist-id="'+esc(p.id)+'">'+(onWish?'♥ SAVED TO WISHLIST':'♡ SAVE TO WISHLIST')+'</button><div class="product-note">Carefully packed for UK delivery.</div></div></div></div>';
root.addEventListener('click',e=>{const add=e.target.closest('[data-product-add]');if(add&&!sold){toggleBag(p.id);add.textContent=inBag(p.id)?'REMOVE FROM BAG':'ADD TO BAG'}});
document.addEventListener('wishlistchange',()=>{const saved=wish().some(x=>String(x)===String(p.id));document.querySelectorAll('[data-wishlist-id="'+CSS.escape(String(p.id))+'"]').forEach(b=>{b.classList.toggle('saved',saved);b.textContent=b.classList.contains('product-wish')?(saved?'♥':'♡'):(saved?'♥ SAVED TO WISHLIST':'♡ SAVE TO WISHLIST')})});
updateCounts()}async function initWishlist(){const ps=await products(),root=$('#wishlistGrid');function render(){const a=wish().map(id=>ps.find(p=>String(p.id)===String(id))).filter(Boolean);root.innerHTML=a.length?a.map(card).join(''):'<div class="empty" style="grid-column:1/-1">Your wishlist is empty.<br><br><a class="btn" href="shop.html">BROWSE THE SHOP</a></div>';wireAdd(ps,root);updateCounts()}render();document.addEventListener('wishlistchange',render)}async function initBag(){const ps=await products(),root=$('#bagRoot');function render(){const a=bag().map(x=>({...x,p:ps.find(p=>String(p.id)===String(x.id))})).filter(x=>x.p);if(!a.length){root.innerHTML='<div class="empty" style="grid-column:1/-1">Your bag is empty.<br><br><a class="btn" href="shop.html">SHOP COLLECTIBLES</a></div>';return}const total=a.reduce((n,x)=>n+x.p.price*x.qty,0);root.innerHTML='<div>'+a.map(x=>'<article class="bag-item"><div class="bag-pic">'+(x.p.image?'<img src="'+esc(x.p.image)+'" alt="">':'')+'</div><div><h3>'+esc(x.p.name)+'</h3><div class="muted">'+money(x.p.price)+' each</div><div class="qty"><button data-minus="'+esc(x.p.id)+'">−</button><b>'+x.qty+'</b><button data-plus="'+esc(x.p.id)+'">+</button><button data-remove="'+esc(x.p.id)+'">REMOVE</button></div></div><strong class="bag-price">'+money(x.p.price*x.qty)+'</strong></article>').join('')+'</div><aside class="summary"><h2>Order Summary</h2><div class="row"><span>Subtotal</span><span>'+money(total)+'</span></div><div class="row"><span>Shipping</span><span>Calculated at checkout</span></div><div class="row total"><span>Total</span><span>'+money(total)+'</span></div><a class="btn" href="checkout.html">CHECKOUT</a></aside>';root.onclick=e=>{const id=e.target.dataset.plus||e.target.dataset.minus||e.target.dataset.remove;if(!id)return;let b=bag(),i=b.findIndex(x=>String(x.id)===String(id));if(e.target.dataset.remove)b.splice(i,1);else if(e.target.dataset.plus)b[i].qty=Math.min(1,+b[i].qty+1);else b[i].qty=Math.max(0,+b[i].qty-1);b=b.filter(x=>x.qty>0);set('funkocouple-bag',b);render();updateCounts()}}render();updateCounts()}document.addEventListener('DOMContentLoaded',()=>{header();const page=document.body.dataset.page;({home:initHome,shop:initShop,product:initProduct,wishlist:initWishlist,bag:initBag}[page]||(()=>{}))()})