const REPO = "Lxixlee/funkocouple.co.uk";
const BRANCH = "main";
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});}
function cookie(name,value,maxAge=3600){return name+"="+value+"; Max-Age="+maxAge+"; Path=/; Secure; HttpOnly; SameSite=Strict";}
async function sign(value,secret){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
async function makeSession(secret){const value=String(Date.now());return value+"."+await sign(value,secret);}
async function validSession(request,secret){const raw=request.headers.get("Cookie")||"";const match=raw.match(/(?:^|; )fc_admin=([^;]+)/);if(!match)return false;const parts=match[1].split(".");if(parts.length!==2)return false;const issued=Number(parts[0]);if(!Number.isFinite(issued)||Date.now()-issued>60*60*1000)return false;return (await sign(parts[0],secret))===parts[1];}
async function github(path,env,options={}){const response=await fetch("https://api.github.com/repos/"+REPO+"/contents/"+path,{...options,headers:{"Authorization":"Bearer "+env.GITHUB_TOKEN,"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"Funko-Couple-Admin",...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"GitHub request failed");return data;}
function requireEnv(env){if(!env.ADMIN_PASSWORD||!env.SESSION_SECRET||!env.GITHUB_TOKEN)throw new Error("Admin Worker secrets are not configured.");}
export default {async fetch(request,env){try{requireEnv(env);const url=new URL(request.url);if(!url.pathname.startsWith("/api/admin"))return new Response("Not found",{status:404});
if(request.method==="POST"&&url.pathname==="/api/admin/login"){const body=await request.json().catch(()=>({}));if(typeof body.password!=="string"||body.password!==env.ADMIN_PASSWORD)return json({ok:false,error:"Incorrect password."},401);const session=await makeSession(env.SESSION_SECRET);return json({ok:true},200,{"Set-Cookie":cookie("fc_admin",session)});}
if(request.method==="POST"&&url.pathname==="/api/admin/logout")return json({ok:true},200,{"Set-Cookie":cookie("fc_admin","",0)});
if(!(await validSession(request,env.SESSION_SECRET)))return json({ok:false,error:"Unauthorised."},401);
if(request.method==="GET"&&url.pathname==="/api/admin/products"){const file=await github("products.json?ref="+BRANCH,env);const products=JSON.parse(atob(file.content.replace(/\n/g,"")));return json({products:Array.isArray(products)?products:[]});}
if(request.method==="PUT"&&url.pathname==="/api/admin/products"){const products=await request.json();if(!Array.isArray(products))return json({ok:false,error:"Products must be an array."},400);const current=await github("products.json?ref="+BRANCH,env);const content=btoa(unescape(encodeURIComponent(JSON.stringify(products,null,2)+"\n")));const saved=await github("products.json",env,{method:"PUT",body:JSON.stringify({message:"Update Funko Couple products",content,sha:current.sha,branch:BRANCH})});return json({ok:true,commit:saved.commit?.sha||null});}
if(request.method==="GET"&&url.pathname==="/api/admin/config"){const file=await github("site-config.json?ref="+BRANCH,env);const config=JSON.parse(atob(file.content.replace(/\n/g,"")));return json({config});}
if(request.method==="PUT"&&url.pathname==="/api/admin/config"){const config=await request.json();const current=await github("site-config.json?ref="+BRANCH,env);const content=btoa(unescape(encodeURIComponent(JSON.stringify(config,null,2)+"\n")));const saved=await github("site-config.json",env,{method:"PUT",body:JSON.stringify({message:"Update Funko Couple category banners",content,sha:current.sha,branch:BRANCH})});return json({ok:true,commit:saved.commit?.sha||null});}
if(request.method==="POST"&&url.pathname==="/api/admin/upload"){const body=await request.json();if(!body.filename||!body.content)return json({ok:false,error:"Missing upload data."},400);const safe=String(body.filename).toLowerCase().replace(/[^a-z0-9._-]/g,"-");const path="assets/banners/"+Date.now()+"-"+safe;const saved=await github(path,env,{method:"PUT",body:JSON.stringify({message:"Upload category banner",content:body.content,branch:BRANCH})});return json({ok:true,image:"https://raw.githubusercontent.com/"+REPO+"/"+BRANCH+"/"+path,commit:saved.commit?.sha||null});}
return json({ok:false,error:"Not found."},404);}catch(error){return json({ok:false,error:error.message||"Server error."},500);}}};